#!/usr/bin/env bash

# Install Nginx web server and redirect to video and custom 404

# Update the package index
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Set up a custom "Hello world" index page
echo "Hello world" | sudo tee /var/www/html/index.html

# Define the redirection rule for /redirect_me
redirection_rule="location /redirect_me {
    return 301 https://github.com/besthor;
}"

# Insert the redirection rule into the Nginx configuration file
sudo sed -i "/server_name _;/a $redirection_rule" /etc/nginx/sites-available/default

# Set up a custom 404 error page with the message "Ceci n'est pas une page"
custom_404_content="Ceci n'est pas une page"
echo "$custom_404_content" | sudo tee /usr/share/nginx/html/custom_404.html

# Define the configuration for the custom 404 error page
custom_404_config="error_page 404 /custom_404.html;
location = /custom_404.html {
    root /usr/share/nginx/html;
    internal;
}"

# Insert the custom 404 error page configuration into the Nginx configuration file
sudo sed -i "/root \/var\/www\/html;/a $custom_404_config" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

